"""Initial migration

Revision ID: b15dd01b76d3
Revises: 
Create Date: 2025-04-10 12:03:27.150494+00:00

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b15dd01b76d3"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tron_requests",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("address", sa.String(), nullable=False, comment="Адрес кошелька."),
        sa.Column(
            "bandwidth",
            sa.Integer(),
            nullable=False,
            comment="Количество использованной пропускной способности.",
        ),
        sa.Column(
            "energy",
            sa.Integer(),
            nullable=False,
            comment="Количество использованной энергии.",
        ),
        sa.Column(
            "trx_balance",
            sa.Numeric(),
            nullable=False,
            comment="Количество TRX на кошельке.",
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP AT TIME ZONE 'UTC')"),
            nullable=False,
            comment="Время создания запроса.",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("tron_requests_pkey")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tron_requests")
    # ### end Alembic commands ###
