name: Ruff линтер проверка

on:
  push:
    branches: ["**"]

jobs:
  lint:
    name: Проверка линтера Ruff
    runs-on: ubuntu-latest

    steps:
      - name: Проверка кода
        uses: actions/checkout@v4

      - name: Установка uv
        uses: astral-sh/setup-uv@v4

      - name: Установка Python
        run: uv python install

      - name: Запуск Ruff
        run: uvx ruff@0.9.1 check . && uvx ruff@0.9.1 check --select I . && uvx ruff@0.9.1 format --check .
