name: Ruff линтер проверка

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  lint:
    name: Проверка линтера Ruff
    runs-on: ubuntu-latest

    steps:
      - name: Проверка кода
        uses: actions/checkout@v3

      - name: Установка Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Установка зависимостей
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]

      - name: Запуск Ruff
        run: ruff .
